# Generated by Django 4.2.7 on 2023-11-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnblisting",
            name="bathrooms",
            field=models.FloatField(),
        ),
    ]
