# Generated by Django 4.2.7 on 2023-11-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_api", "0002_alter_airbnblisting_bathrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnblisting",
            name="airbnb_property_id",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="airbnblisting",
            name="vrbo_property_id",
            field=models.CharField(null=True),
        ),
    ]
