# Generated by Django 4.2.7 on 2023-11-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_api", "0003_alter_airbnblisting_airbnb_property_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnblisting",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airbnblisting",
            name="reviews",
            field=models.IntegerField(null=True),
        ),
    ]
