# Generated by Django 4.2.7 on 2023-11-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_api", "0004_alter_airbnblisting_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnblisting",
            name="bathrooms",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="airbnblisting",
            name="market_name",
            field=models.CharField(null=True),
        ),
    ]
