# Generated by Django 4.2.7 on 2023-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airbnb_api", "0005_alter_airbnblisting_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airbnblisting",
            name="host",
            field=models.CharField(default="host1"),
            preserve_default=False,
        ),
    ]
